version: '3.9'

services:
  nest:
    container_name: nest
    image: rss/nest
    build: .
    restart: always
    environment:
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - logs:/app/logs
      - ./src:/app/src
      - files:/app/files
    networks:
      - rss-network
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: rss/postgres
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - rss-network
volumes:
  logs:
  postgres-db:
  files:
networks:
  rss-network:
    name: rss-network
    driver: bridge
