version: '3.9'

services:
  nodejs2021q4-service:
    image: nodejs2021q4-service
    deploy:
      restart_policy:
        condition: on-failure
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app/src
      - /usr/app/node_modules
      - ./logs:/usr/app/logs
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
  postgres:
    build: ./db
    image: postgres
    environment:
      POSTGRES_DB: "app-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/usr/app/pgdata"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

networks:
  nodejs2021q4-network:
   name: nodejs2021q4
